// src/WebSocketTester.js
import React, { useState } from 'react';
import { useWebSocket } from '../hooks';
import { arrayBufferToBase64 } from '../utils';

const WebSocketTester = () => {
  const [messages, setMessages] = useState([]);
  const [inputValue, setInputValue] = useState('');
  const { ws, sendMessage } = useWebSocket('ws://localhost:8765');

  const sendRandomByteArray = () => {
    const byteArray = new Uint8Array(10);
    window.crypto.getRandomValues(byteArray);
    console.log('Generated byte array:', byteArray);

    const base64ByteArray = arrayBufferToBase64(byteArray.buffer);
    const _package = {
        type: 'audio',
        from: 'user',
        data: base64ByteArray,
    };
    const message = JSON.stringify(_package);
    console.log('Sending message:', message);
    sendMessage(message);
  }

  return (
    <div>
      <h1>WebSocket Chat</h1>
      <div>
        {messages.map((message, index) => (
          <div key={index}>{message}</div>
        ))}
      </div>
      <input
        type="text"
        value={inputValue}
        onChange={(e) => setInputValue(e.target.value)}
      />
      <button onClick={() => sendRandomByteArray()}>Send</button>
    </div>
  );
};

export default WebSocketTester;